function f = dynamics(obj,in1,in2)
%DYNAMICS
%    F = DYNAMICS(IN1,IN2,GRAV,M_BODY,I_BODY,B_HIP,M_THIGH,R_THIGH,I_THIGH,B_ROT,M_ROT,K_LEG,B_LEG,M_TOE)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    20-Sep-2017 15:26:26

q1 = in1(1,:);
q2 = in1(2,:);
q4 = in1(4,:);
qdot1 = in2(1,:);
qdot2 = in2(2,:);
t2 = q1.^2;
t3 = t2.^2;
t4 = t3.^2;
t5 = q2.^2;
t6 = t2+t5;
t7 = t5.^2;
t8 = t6.^(5.0./2.0);
t9 = t7.^2;
t10 = 1.0./sqrt(t6);
t11 = qdot1.^2;
t12 = qdot2.^2;
t13 = 1.0./t6.^2;
t14 = 1.0./q2;
t15 = 1.0./t6.^3;
t16 = 1.0./t6.^(3.0./2.0);
t17 = 1.0./t6.^(5.0./2.0);
f = [1.0./t6.^(1.1e1./2.0).*(obj.I_thigh.*q1.*t5.*t8.*t11.*-2.0+obj.I_thigh.*q1.*t5.*t8.*t12.*2.0-obj.k_leg.*q1.*q4.*t2.*t4-obj.k_leg.*q1.*q4.*t4.*t5.*5.0-obj.k_leg.*q1.*q4.*t2.*t9.*5.0-obj.k_leg.*q1.*q4.*t5.*t9+obj.k_leg.*q1.*t2.*t3.*t8+obj.k_leg.*q1.*t3.*t5.*t8.*3.0+obj.k_leg.*q1.*t2.*t7.*t8.*3.0+obj.k_leg.*q1.*t5.*t7.*t8-obj.k_leg.*q1.*q4.*t2.*t3.*t7.*1.0e1-obj.k_leg.*q1.*q4.*t3.*t5.*t7.*1.0e1+obj.I_thigh.*q2.*qdot1.*qdot2.*t2.*t8.*2.0-obj.I_thigh.*q2.*qdot1.*qdot2.*t5.*t8.*2.0+obj.grav.*obj.m_thigh.*q1.*q2.*obj.r_thigh.*t4+obj.grav.*obj.m_thigh.*q1.*q2.*obj.r_thigh.*t9+obj.grav.*obj.m_thigh.*q1.*q2.*obj.r_thigh.*t3.*t7.*6.0+obj.grav.*obj.m_thigh.*q1.*q2.*obj.r_thigh.*t2.*t3.*t5.*4.0+obj.grav.*obj.m_thigh.*q1.*q2.*obj.r_thigh.*t2.*t5.*t7.*4.0);obj.grav.*obj.m_body+obj.grav.*obj.m_thigh+obj.k_leg.*q2-obj.grav.*obj.m_thigh.*obj.r_thigh.*t10-obj.k_leg.*q2.*q4.*t10+obj.I_thigh.*q1.*qdot1.*qdot2.*t13.*2.0+obj.I_thigh.*q2.*t2.*t11.*t15.*2.0-obj.I_thigh.*t2.*t12.*t13.*t14.*2.0+obj.I_thigh.*t3.*t12.*t14.*t15.*2.0+obj.grav.*obj.m_thigh.*obj.r_thigh.*t5.*t16-obj.m_thigh.*q1.*qdot1.*obj.r_thigh.*t16.*(3.0./2.0)+obj.m_thigh.*q2.*qdot1.*obj.r_thigh.*t16.*(3.0./2.0)+obj.m_thigh.*q1.*qdot1.*obj.r_thigh.*t2.*t17.*(3.0./2.0)-obj.m_thigh.*q2.*qdot1.*obj.r_thigh.*t2.*t17.*(3.0./2.0)+obj.m_thigh.*q1.*qdot1.*obj.r_thigh.*t5.*t17.*(3.0./2.0)-obj.m_thigh.*q2.*qdot1.*obj.r_thigh.*t5.*t17.*(3.0./2.0)-obj.I_thigh.*q1.*qdot1.*qdot2.*t2.*t15.*4.0;0.0;obj.k_leg.*(q4.*2.0-sqrt(t6).*2.0).*(1.0./2.0)];
