function f = jacobian(obj,in1)
%JACOBIAN
%    F = JACOBIAN(IN1,GRAV,M_BODY,I_BODY,B_HIP,M_THIGH,R_THIGH,I_THIGH,B_ROT,M_ROT,K_LEG,B_LEG,M_TOE)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    15-Sep-2017 14:25:39

f = zeros(0,4);
