function f = massMatrix(obj,in1)
%MASSMATRIX
%    F = MASSMATRIX(IN1,GRAV,M_BODY,I_BODY,B_HIP,M_THIGH,R_THIGH,I_THIGH,B_ROT,M_ROT,K_LEG,B_LEG,M_TOE)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    19-Sep-2017 11:03:44

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q2.^2;
t3 = q1.^2;
t4 = t2+t3;
t5 = t3.^2;
t6 = t4.^(5.0./2.0);
t7 = t2.^2;
t8 = 1.0./t4.^(1.1e1./2.0);
t9 = 1.0./t4.^2;
f = reshape([t8.*(obj.I_thigh.*t6.*t7+obj.I_thigh.*t2.*t3.*t6+obj.m_body.*t2.*t5.*t6.*3.0+obj.m_body.*t3.*t5.*t6+obj.m_body.*t2.*t6.*t7+obj.m_body.*t3.*t6.*t7.*3.0),-obj.I_thigh.*q1.*q2.*t9,0.0,0.0,-t8.*(obj.I_thigh.*q1.*q2.*t2.*t6+obj.I_thigh.*q1.*q2.*t3.*t6),obj.m_body+obj.I_thigh.*t3.*t9,0.0,0.0,0.0,0.0,obj.I_body,0.0,0.0,0.0,0.0,obj.m_rot],[4,4]);
