function [ ctrlParamLbls ] = impulseControllerParamLabels( )
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

ctrlParamLbls = {'Desired Leg Length',...
                 'Desired Body Angle',...
                 'Desired Swing Leg Angle',...
                 'Lookup Table Swing Leg Angle',...
                 'Measured Foot Impulse',...
                 'Measured Foot Force',...
                 'Measured Foot Force dot',...
                 'Desired Foot Impulse',...
                 'Desired Foot Force',...
                 'Desired Foot Force dot'};
end

